@startuml
'https://plantuml.com/sequence-diagram

autonumber

WEB ->  CONTRACT_CENTER: 获取已完结合同列表
WEB ->  WEB: 未评价展示评价按钮
WEB ->  WEB: 点击评价，弹出评价弹窗
WEB ->  CONTRACT_CENTER: 评价
CONTRACT_CENTER -> CONTRACT_CENTER :更新合同评价状态，添加t_contract_status_flow记录
CONTRACT_CENTER->CONFIG:发送该合同评价信息至通用能力
CONFIG->CONFIG:记录合同评价信息，供后续评价信息查询


@enduml